name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 and Maven
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 8
        java-distribution: temurin
        maven-version: 3.8.7
    - name: Compilando CÃ³digo...
      run: mvn compile

    - name: Testando...
      run: mvn test

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
